[package]
name = "rocky_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
rocky_core = { path = "../core" }
serde_json = "1.0.145"
tokio = "1.48.0"
