[package]
name = "rocky_scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
rocky_core = { path = "../core" }
rocky_storage = { path = "../storage" }

futures = "0.3.31"
serde_json = "1.0.145"
tokio = "1.48.0"
